# Site settings
title: Partyzantów 29
email: partyzantow29@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://partyzantow29.github.io/" # the base hostname & protocol for your site

# User setting
email: partyzantow29@gmail.com
address:
  - line: ul. Partyzantów 29
  - line: Busko-Zdrój
  # Feel free to add more lines here 

copyright: partyzantow29

# API settings
google_api_key: AIzaSyBRPF5mO3DXvZ8aARZqYcX061amO8f3oPQ

# Build settings
markdown: kramdown